#!/usr/bin/env python3
"""
microdragon/modules/document/create.py
═══════════════════════════════════════════════════════════════════════════════
MICRODRAGON Document Creator
Creates real .docx, .xlsx, .pdf, .pptx files from AI-generated content.

Usage (called by Rust shell tool):
  python3 modules/document/create.py docx "My Report" "content..." output.docx
  python3 modules/document/create.py xlsx "Budget" "col1,col2|row1a,row1b" output.xlsx
  python3 modules/document/create.py pdf "content..." output.pdf
  python3 modules/document/create.py pptx "title|slide1_content|slide2_content" output.pptx

© 2026 EMEMZYVISUALS DIGITALS — Emmanuel Ariyo
"""

import sys
import os
import json
from pathlib import Path


# ─── DOCX creator ─────────────────────────────────────────────────────────────

def create_docx(title: str, content: str, output_path: str) -> str:
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.style import WD_STYLE_TYPE
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        import datetime
    except ImportError:
        return "ERROR: python-docx not installed. Run: pip install python-docx"

    doc = Document()

    # Document properties
    core = doc.core_properties
    core.title = title
    core.author = "MICRODRAGON — EMEMZYVISUALS DIGITALS"
    core.created = datetime.datetime.now()

    # Title
    heading = doc.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in heading.runs:
        run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    # Subtitle / date
    sub = doc.add_paragraph(f"Generated by MICRODRAGON • {datetime.date.today()}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in sub.runs:
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # spacer

    # Parse content into sections
    lines = content.strip().split('\n')
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if not line:
            doc.add_paragraph()
            i += 1
            continue

        # Markdown-style headings
        if line.startswith('# '):
            doc.add_heading(line[2:].strip(), level=1)
        elif line.startswith('## '):
            doc.add_heading(line[3:].strip(), level=2)
        elif line.startswith('### '):
            doc.add_heading(line[4:].strip(), level=3)
        # Bullet points
        elif line.startswith('- ') or line.startswith('* '):
            doc.add_paragraph(line[2:].strip(), style='List Bullet')
        # Numbered list
        elif len(line) > 2 and line[0].isdigit() and line[1] in '.):':
            doc.add_paragraph(line[2:].strip() if len(line) > 2 else line, style='List Number')
        # Code block start
        elif line.startswith('```'):
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith('```'):
                code_lines.append(lines[i])
                i += 1
            # Add code paragraph
            code_para = doc.add_paragraph('\n'.join(code_lines))
            code_para.style = 'Normal'
            for run in code_para.runs:
                run.font.name = 'Courier New'
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(0x2d, 0x2d, 0x2d)
        # Bold text **...**
        elif '**' in line:
            para = doc.add_paragraph()
            parts = line.split('**')
            for j, part in enumerate(parts):
                run = para.add_run(part)
                run.bold = (j % 2 == 1)
        else:
            doc.add_paragraph(line)

        i += 1

    # Footer
    section = doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = f"MICRODRAGON — EMEMZYVISUALS DIGITALS  •  {title}"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    doc.save(output_path)
    size_kb = Path(output_path).stat().st_size / 1024
    return f"✓ Word document created: {output_path} ({size_kb:.1f}KB)"


# ─── XLSX creator ─────────────────────────────────────────────────────────────

def create_xlsx(title: str, content: str, output_path: str) -> str:
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side, numbers
        from openpyxl.utils import get_column_letter
        import json
    except ImportError:
        return "ERROR: openpyxl not installed. Run: pip install openpyxl"

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = title[:31]  # Excel sheet name limit

    # Parse content as JSON data or CSV-style
    rows_data = []
    headers = []

    try:
        data = json.loads(content)
        if isinstance(data, dict):
            # Dict of columns
            if 'headers' in data:
                headers = data['headers']
            if 'rows' in data:
                rows_data = data['rows']
            elif 'data' in data:
                rows_data = data['data']
        elif isinstance(data, list):
            if data and isinstance(data[0], dict):
                headers = list(data[0].keys())
                rows_data = [[row.get(h, '') for h in headers] for row in data]
            else:
                rows_data = data
    except (json.JSONDecodeError, TypeError):
        # Parse as pipe-delimited CSV (col1|col2\nrow1a|row1b)
        lines = [l.strip() for l in content.strip().split('\n') if l.strip()]
        if lines:
            headers = [h.strip() for h in lines[0].split('|')]
            rows_data = [[c.strip() for c in line.split('|')] for line in lines[1:]]

    # Style definitions
    header_fill   = PatternFill("solid", fgColor="1a1a2e")
    header_font   = Font(bold=True, color="FFFFFF", size=11)
    alt_fill      = PatternFill("solid", fgColor="F0F4FF")
    title_font    = Font(bold=True, size=14, color="1a1a2e")
    border_side   = Side(style='thin', color='CCCCCC')
    cell_border   = Border(left=border_side, right=border_side,
                           top=border_side, bottom=border_side)

    # Title row
    ws['A1'] = title
    ws['A1'].font = title_font
    ws['A1'].alignment = Alignment(horizontal='center')
    if headers:
        ws.merge_cells(f'A1:{get_column_letter(max(len(headers), 1))}1')
    ws.row_dimensions[1].height = 30

    # Headers row
    if headers:
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=2, column=col_idx, value=header)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center', vertical='center')
            cell.border = cell_border
        ws.row_dimensions[2].height = 22

    # Data rows
    for row_idx, row in enumerate(rows_data, 3):
        for col_idx, value in enumerate(row, 1):
            cell = ws.cell(row=row_idx, column=col_idx)
            # Try to set as number if it looks numeric
            try:
                cell.value = float(value) if '.' in str(value) else int(value)
            except (ValueError, TypeError):
                cell.value = value
            # Alternate row shading
            if row_idx % 2 == 0:
                cell.fill = alt_fill
            cell.border = cell_border
            cell.alignment = Alignment(vertical='center')

    # Auto-width columns
    for col_idx in range(1, max(len(headers), 1) + 1):
        col_letter = get_column_letter(col_idx)
        max_width = 0
        for row in ws.iter_rows(min_col=col_idx, max_col=col_idx):
            for cell in row:
                if cell.value:
                    max_width = max(max_width, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_width + 4, 40)

    # Freeze header rows
    ws.freeze_panes = 'A3'

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)
    size_kb = Path(output_path).stat().st_size / 1024
    return f"✓ Excel spreadsheet created: {output_path} ({size_kb:.1f}KB)"


# ─── PDF creator ──────────────────────────────────────────────────────────────

def create_pdf(title: str, content: str, output_path: str) -> str:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch, cm
        from reportlab.lib import colors
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        HRFlowable, ListFlowable, ListItem,
                                        Preformatted)
        from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
        import datetime
    except ImportError:
        return "ERROR: reportlab not installed. Run: pip install reportlab"

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle('MTitle',
        parent=styles['Title'],
        fontSize=24, textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=8, spaceBefore=0, alignment=TA_CENTER)

    h1_style = ParagraphStyle('MH1',
        parent=styles['Heading1'],
        fontSize=16, textColor=colors.HexColor('#1a1a2e'),
        spaceBefore=14, spaceAfter=6,
        borderPad=4)

    h2_style = ParagraphStyle('MH2',
        parent=styles['Heading2'],
        fontSize=13, textColor=colors.HexColor('#2d5a8e'),
        spaceBefore=10, spaceAfter=4)

    body_style = ParagraphStyle('MBody',
        parent=styles['Normal'],
        fontSize=11, leading=16,
        spaceAfter=6, alignment=TA_JUSTIFY)

    code_style = ParagraphStyle('MCode',
        parent=styles['Code'],
        fontSize=9, fontName='Courier',
        backColor=colors.HexColor('#f4f4f8'),
        leftIndent=20, spaceAfter=8)

    bullet_style = ParagraphStyle('MBullet',
        parent=body_style,
        leftIndent=20, bulletIndent=10,
        spaceAfter=3)

    story = []

    # Title
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(
        f"Generated by MICRODRAGON • EMEMZYVISUALS DIGITALS • {datetime.date.today()}",
        ParagraphStyle('MSubtitle', parent=styles['Normal'],
                       fontSize=9, textColor=colors.grey, alignment=TA_CENTER)
    ))
    story.append(HRFlowable(width="100%", thickness=1,
                              color=colors.HexColor('#1a1a2e'), spaceAfter=14))

    # Parse content
    lines = content.strip().split('\n')
    i = 0
    bullet_group = []

    def flush_bullets():
        if bullet_group:
            for b in bullet_group:
                story.append(Paragraph(f"• {b}", bullet_style))
            bullet_group.clear()
            story.append(Spacer(1, 4))

    while i < len(lines):
        line = lines[i].strip()

        if not line:
            flush_bullets()
            story.append(Spacer(1, 6))
            i += 1
            continue

        if line.startswith('# '):
            flush_bullets()
            story.append(Paragraph(line[2:].strip(), h1_style))
            story.append(HRFlowable(width="100%", thickness=0.5,
                                     color=colors.HexColor('#cccccc'), spaceAfter=4))
        elif line.startswith('## '):
            flush_bullets()
            story.append(Paragraph(line[3:].strip(), h2_style))
        elif line.startswith('### '):
            flush_bullets()
            story.append(Paragraph(f"<b>{line[4:].strip()}</b>", body_style))
        elif line.startswith('- ') or line.startswith('* '):
            bullet_group.append(line[2:].strip())
        elif line.startswith('```'):
            flush_bullets()
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith('```'):
                code_lines.append(lines[i])
                i += 1
            if code_lines:
                story.append(Preformatted('\n'.join(code_lines), code_style))
        else:
            flush_bullets()
            # Handle **bold** inline
            text = line.replace('**', '<b>', 1)
            text = text.replace('**', '</b>', 1) if '<b>' in text else text
            story.append(Paragraph(text, body_style))

        i += 1

    flush_bullets()

    # Build PDF
    doc.build(story)
    size_kb = Path(output_path).stat().st_size / 1024
    return f"✓ PDF created: {output_path} ({size_kb:.1f}KB)"


# ─── PPTX creator ─────────────────────────────────────────────────────────────

def create_pptx(title: str, content: str, output_path: str) -> str:
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt, Emu
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        import json
    except ImportError:
        return "ERROR: python-pptx not installed. Run: pip install python-pptx"

    prs = Presentation()
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.5)

    # Parse slides from content (delimited by --slide-- or |)
    if '--slide--' in content:
        slides_raw = content.split('--slide--')
    elif '\n\n' in content:
        slides_raw = [s.strip() for s in content.split('\n\n') if s.strip()]
    else:
        slides_raw = [content]

    BRAND_DARK   = RGBColor(0x1a, 0x1a, 0x2e)
    BRAND_GREEN  = RGBColor(0x00, 0xff, 0x88)
    BRAND_LIGHT  = RGBColor(0xf0, 0xf4, 0xff)

    def add_title_slide(prs, title_text, subtitle="MICRODRAGON — EMEMZYVISUALS DIGITALS"):
        layout = prs.slide_layouts[6]  # Blank
        slide = prs.slides.add_slide(layout)
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = BRAND_DARK

        # Title
        txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11), Inches(2))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = title_text
        p.alignment = PP_ALIGN.CENTER
        run = p.runs[0]
        run.font.size = Pt(44)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0xff, 0xff, 0xff)

        # Subtitle
        txBox2 = slide.shapes.add_textbox(Inches(1), Inches(5), Inches(11), Inches(1))
        tf2 = txBox2.text_frame
        p2 = tf2.paragraphs[0]
        p2.text = subtitle
        p2.alignment = PP_ALIGN.CENTER
        p2.runs[0].font.size = Pt(16)
        p2.runs[0].font.color.rgb = BRAND_GREEN
        return slide

    def add_content_slide(prs, slide_title, slide_content):
        layout = prs.slide_layouts[6]  # Blank
        slide = prs.slides.add_slide(layout)

        # Header bar
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(0xf8, 0xf9, 0xff)

        # Header
        hdr = slide.shapes.add_textbox(Inches(0.3), Inches(0.2), Inches(12.5), Inches(0.9))
        tf = hdr.text_frame
        p = tf.paragraphs[0]
        p.text = slide_title
        run = p.runs[0]
        run.font.size = Pt(28)
        run.font.bold = True
        run.font.color.rgb = BRAND_DARK

        # Content
        content_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.3), Inches(12.3), Inches(5.5))
        ctf = content_box.text_frame
        ctf.word_wrap = True

        bullet_lines = [l.strip() for l in slide_content.split('\n') if l.strip()]
        first = True
        for line in bullet_lines:
            if first:
                p = ctf.paragraphs[0]
                first = False
            else:
                p = ctf.add_paragraph()

            is_bullet = line.startswith('- ') or line.startswith('• ')
            text = line[2:].strip() if is_bullet else line

            p.text = ("• " if is_bullet else "") + text
            run = p.runs[0] if p.runs else p.add_run()
            run.font.size = Pt(18)
            run.font.color.rgb = BRAND_DARK

        return slide

    # Add title slide
    add_title_slide(prs, title)

    # Add content slides
    for raw_slide in slides_raw:
        lines = [l.strip() for l in raw_slide.strip().split('\n') if l.strip()]
        if not lines:
            continue
        slide_title = lines[0].lstrip('#').strip()
        slide_body = '\n'.join(lines[1:]) if len(lines) > 1 else ""
        add_content_slide(prs, slide_title, slide_body)

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    prs.save(output_path)
    size_kb = Path(output_path).stat().st_size / 1024
    return f"✓ PowerPoint created: {output_path} ({size_kb:.1f}KB)"


# ─── SVG / HTML design ────────────────────────────────────────────────────────

def create_html(title: str, content: str, output_path: str) -> str:
    """Write HTML/CSS content to file."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding='utf-8')
    size_kb = Path(output_path).stat().st_size / 1024
    return f"✓ HTML file created: {output_path} ({size_kb:.1f}KB)"


def create_svg(title: str, content: str, output_path: str) -> str:
    """Write SVG content to file."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding='utf-8')
    size_kb = Path(output_path).stat().st_size / 1024
    return f"✓ SVG file created: {output_path} ({size_kb:.1f}KB)"


# ─── Entry point ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: create.py <format> <title> <content> <output_path>")
        print("Formats: docx, xlsx, pdf, pptx, html, svg")
        sys.exit(1)

    fmt         = sys.argv[1].lower()
    title       = sys.argv[2]
    content     = sys.argv[3]
    output_path = sys.argv[4]

    if fmt == "docx":
        result = create_docx(title, content, output_path)
    elif fmt == "xlsx":
        result = create_xlsx(title, content, output_path)
    elif fmt == "pdf":
        result = create_pdf(title, content, output_path)
    elif fmt == "pptx":
        result = create_pptx(title, content, output_path)
    elif fmt == "html":
        result = create_html(title, content, output_path)
    elif fmt == "svg":
        result = create_svg(title, content, output_path)
    else:
        result = f"ERROR: Unknown format '{fmt}'. Use: docx, xlsx, pdf, pptx, html, svg"

    print(result)
